### ISSUE TITLE
Graph Execution Error

### ISSUE THREAD

**Issue by ShadowVicky** [HarishValliappan/Gun-classification-using-gunshot#1]
Epoch 1/20
/usr/local/lib/python3.10/dist-packages/keras/src/backend.py:5714: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
[<ipython-input-26-c4c43c011f08>](https://localhost:8080/#) in <cell line: 1>()
----> 1 history = my_model.fit(train_ds,epochs=20, validation_data = val_ds)

1 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     51   try:
     52     ctx.ensure_initialized()
---> 53     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     54                                         inputs, attrs, num_outputs)
     55   except core._NotOkStatusException as e:

NotFoundError: Graph execution error:
I am getting this error while running the code
how can i solve it?
pls help

**Comment by HarishValliappan** [comment]
Cleanly once check your csv file, all column details , any small column names gives this Graph execution error.
It is a biniary or multiclass classification?

**Comment by ShadowVicky** [comment]
It is a multiclass classification..
In my dataset i have 4 folders with 4 classes.

**Comment by HarishValliappan** [comment]
once check your last layer nodes , you should have 4 nodes
check your excel file once.
